// <auto-generated />
using System;
using FinalProjectLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250508140202_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectLibrary.Models.Books.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"), 1001L);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("BookDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookStatus")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1001,
                            Author = "F. Scott Fitzgerald",
                            BookDescription = "Lorem Ipsum",
                            BookStatus = 0,
                            Genre = 8,
                            PublicationYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookID = 1002,
                            Author = "Harper Lee",
                            BookDescription = "Lorem Ipsum",
                            BookStatus = 0,
                            Genre = 8,
                            PublicationYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookID = 1003,
                            Author = "George Orwell",
                            BookDescription = "Lorem Ipsum",
                            BookStatus = 0,
                            Genre = 8,
                            PublicationYear = 1949,
                            Title = "1984"
                        });
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.History.CheckedOutItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReminderEmailSent")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("CheckOutItems");
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.History.ReservationItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1001L);

                    b.Property<DateTime?>("AvailabilityDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BookIsAvaliableEmailSent")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BookID");

                    b.HasIndex("UserID");

                    b.ToTable("ReservationItems");
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.History.StatusHistoryItem", b =>
                {
                    b.Property<int>("StatusHistoryItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusHistoryItemID"), 1001L);

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("BookStatus")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("StatusHistoryItemID");

                    b.HasIndex("BookID");

                    b.HasIndex("UserID");

                    b.ToTable("StatusHistoryItems");

                    b.HasData(
                        new
                        {
                            StatusHistoryItemID = 1001,
                            BookID = 1001,
                            BookStatus = 0,
                            Notes = "Initial status",
                            Timestamp = new DateTime(2025, 5, 7, 14, 2, 2, 393, DateTimeKind.Utc).AddTicks(5683)
                        },
                        new
                        {
                            StatusHistoryItemID = 1002,
                            BookID = 1002,
                            BookStatus = 2,
                            Notes = "Initial status",
                            Timestamp = new DateTime(2025, 5, 6, 14, 2, 2, 393, DateTimeKind.Utc).AddTicks(5688)
                        },
                        new
                        {
                            StatusHistoryItemID = 1003,
                            BookID = 1003,
                            BookStatus = 1,
                            Notes = "Initial status",
                            Timestamp = new DateTime(2025, 5, 5, 14, 2, 2, 393, DateTimeKind.Utc).AddTicks(5690)
                        });
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.Users.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1001L);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.History.CheckedOutItem", b =>
                {
                    b.HasOne("FinalProjectLibrary.Models.Books.Book", "Book")
                        .WithOne("CheckedOutBy")
                        .HasForeignKey("FinalProjectLibrary.Models.History.CheckedOutItem", "BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProjectLibrary.Models.Users.User", "User")
                        .WithMany("CheckedOutBooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.History.ReservationItem", b =>
                {
                    b.HasOne("FinalProjectLibrary.Models.Books.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProjectLibrary.Models.Users.User", "User")
                        .WithMany("ReservedBooks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.History.StatusHistoryItem", b =>
                {
                    b.HasOne("FinalProjectLibrary.Models.Books.Book", "Book")
                        .WithMany("StatusHistory")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProjectLibrary.Models.Users.User", "User")
                        .WithMany("UserHistory")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.Books.Book", b =>
                {
                    b.Navigation("CheckedOutBy");

                    b.Navigation("Reservations");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.Users.User", b =>
                {
                    b.Navigation("CheckedOutBooks");

                    b.Navigation("ReservedBooks");

                    b.Navigation("UserHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
