// <auto-generated />
using System;
using FinalProjectLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250506173609_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectLibrary.Models.Books.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("BookDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookStatus")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasMaxLength(25)
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 101,
                            Author = "F. Scott Fitzgerald",
                            BookDescription = "Lorem Ipsum",
                            BookStatus = 0,
                            Genre = 8,
                            PublicationYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookID = 102,
                            Author = "Harper Lee",
                            BookDescription = "Lorem Ipsum",
                            BookStatus = 0,
                            Genre = 8,
                            PublicationYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookID = 103,
                            Author = "George Orwell",
                            BookDescription = "Lorem Ipsum",
                            BookStatus = 0,
                            Genre = 8,
                            PublicationYear = 1949,
                            Title = "1984"
                        });
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.StatusHistoryItem", b =>
                {
                    b.Property<int>("StatusHistoryItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusHistoryItemID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("BookStatus")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("StatusHistoryItemID");

                    b.HasIndex("BookID");

                    b.HasIndex("UserID");

                    b.ToTable("StatusHistoryItems");

                    b.HasData(
                        new
                        {
                            StatusHistoryItemID = 1,
                            BookID = 101,
                            BookStatus = 0,
                            Notes = "Initial status",
                            Timestamp = new DateTime(2025, 5, 5, 17, 36, 8, 938, DateTimeKind.Utc).AddTicks(7385)
                        },
                        new
                        {
                            StatusHistoryItemID = 2,
                            BookID = 102,
                            BookStatus = 2,
                            Notes = "Initial status",
                            Timestamp = new DateTime(2025, 5, 4, 17, 36, 8, 938, DateTimeKind.Utc).AddTicks(7389)
                        },
                        new
                        {
                            StatusHistoryItemID = 3,
                            BookID = 103,
                            BookStatus = 1,
                            Notes = "Initial status",
                            Timestamp = new DateTime(2025, 5, 3, 17, 36, 8, 938, DateTimeKind.Utc).AddTicks(7390)
                        });
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.Users.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1001L);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.StatusHistoryItem", b =>
                {
                    b.HasOne("FinalProjectLibrary.Models.Books.Book", "book")
                        .WithMany("StatusHistory")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProjectLibrary.Models.Users.User", "user")
                        .WithMany("UserHistory")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("book");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.Books.Book", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("FinalProjectLibrary.Models.Users.User", b =>
                {
                    b.Navigation("UserHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
